algoritmo "exercicio-A"
// Disciplina  : Linguagem e Lógica de Programação com JS
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Ryan de Almeida da Silva
// Data atual  : 25/03/2024
var

condicao:inteiro

inicio

condicao <- 1

enquanto condicao <= 10 faca
escreval(condicao ," X 5 =", condicao*5)
condicao <- condicao + 1
fimenquanto

fimalgoritmo