algoritmo "exercicio-G"
// Disciplina  : Linguagem e Lógica de Programação com JS
// Professor   : Jailson Costa dos Santos
// Descrição   : desc
// Autor(a)    : Ryan de Almeida da Silva
// Data atual  : 25/03/2024
var

   contadora, resultado:inteiro

inicio

   para contadora de 0 ate 15 faca
      se contadora = 0 entao
         resultado <- 1
      senao
         resultado <- resultado * 3
      fimse
      escreval(resultado)
   fimpara

fimalgoritmo