algoritmo "exercicio-J"
// Disciplina  : Linguagem e Lógica de Programação com JS
// Professor   : Jailson Costa dos Santos
// Descrição   : desc
// Autor(a)    : Ryan de Almeida da Silva
// Data atual  : 25/03/2024
var

celsius:inteiro
fahrenheit:real

inicio

para celsius de 10 ate 100 passo 10 faca

fahrenheit <- (9 * celsius + 160) / 5
escreval(celsius ,"Cº ===", fahrenheit ,"Fº")
fimpara


fimalgoritmo