algoritmo "exercicio-E"
// Disciplina  : Linguagem e Lógica de Programação com JS
// Professor   : Jailson Costa dos Santos
// Descrição   : desc
// Autor(a)    : Ryan de Almeida da Silva
// Data atual  : 25/03/2024
var

contadora, soma:inteiro

inicio

   para contadora de 1 ate 20 passo 1 faca
      se contadora % 2 = 1 entao
         soma <- soma + contadora
      fimse
   fimpara

   escreval(soma)

fimalgoritmo