algoritmo "exercicio-F"
// Disciplina  : Linguagem e Lógica de Programação com JS
// Professor   : Jailson Costa dos Santos
// Descrição   : desc
// Autor(a)    : Ryan de Almeida da Silva
// Data atual  : 25/03/2024
var

   contadora:inteiro

inicio

   para contadora de 1 ate 200 passo 1 faca
      se contadora % 4 = 0 entao
         escreval(contadora)
      fimse
   fimpara

fimalgoritmo